name: build and push docker images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: sigoden
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: ./base/Dockerfile
          push: true
          tags: sigoden/node:14
      - name: Build and push native
        uses: docker/build-push-action@v2
        with:
          context: ./native
          file: ./native/Dockerfile
          push: true
          tags: sigoden/node:14-native
      - name: Build and push native
        uses: docker/build-push-action@v2
        with:
          context: ./slim
          file: ./slim/Dockerfile
          push: true
          tags: sigoden/node:14-slim